#pragma once

enum XACT_WAVEBANK_BGM : unsigned int
{
    XACT_WAVEBANK_BGM_TITLE = 0,
    XACT_WAVEBANK_BGM_SELECT = 1,
    XACT_WAVEBANK_BGM_PLAY = 2,
    XACT_WAVEBANK_BGM_RESULT = 3,
};

#define XACT_WAVEBANK_BGM_ENTRY_COUNT 4
