#pragma once

enum XACT_WAVEBANK_SE : unsigned int
{
    XACT_WAVEBANK_SE_MOVECURSOL = 0,
    XACT_WAVEBANK_SE_DECISION = 1,
    XACT_WAVEBANK_SE_JUMP = 2,
    XACT_WAVEBANK_SE_DIMENSIONCHANGE = 3,
    XACT_WAVEBANK_SE_FALL = 4,
    XACT_WAVEBANK_SE_CAMERAROTATION = 5,
};

#define XACT_WAVEBANK_SE_ENTRY_COUNT 6
